### ISSUE TITLE
[Bug]: get_code doesn't return dependencies of the lines with # @linksto

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal.data#261] opened 2024-01-19 15:43 UTC
### What happened?

```r
tdata <- teal_data() |>
  eval_code("
    foo <- function() {
      env <- parent.frame()
      env$x <- 0
    }
    foo() # @linksto x
    y <- x
  ")
  
  
get_code(tdata, datanames = "x")
# character(0)
```

In this case get_code should return all the code

**Comment by gogonzo** [comment] 2024-01-19 17:24
I was trying to fix this problem but it is more complex. Something to talk on monday

**Comment by donyunardi** [comment] 2024-01-19 18:27
@gogonzo I can't reproduce your result as I got `foo()` returned. 

``` r
library(teal.data)
#> Loading required package: teal.code
tdata <- teal_data() |>
  eval_code("
    foo <- function() {
      env <- parent.frame()
      env$x <- 0
    }
    foo() # @linksto x
    y <- x
  ")  
  
get_code(tdata, datanames = "x")
#> [1] "foo()"
```

<sup>Created on 2024-01-19 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I have latest `main` for teal.data

<details>

<summary> SessionInfo() </summary>

```r
R version 4.3.2 (2023-10-31)
Platform: x86_64-apple-darwin20 (64-bit)
Running under: macOS Ventura 13.6.3

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: America/Los_Angeles
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] teal.data_0.3.0.9039 teal.code_0.5.0.9000

loaded via a namespace (and not attached):
 [1] vctrs_0.6.5       cli_3.6.2         knitr_1.44        rlang_1.1.2       xfun_0.40         processx_3.8.2   
 [7] purrr_1.0.2       styler_1.10.2     glue_1.6.2        backports_1.4.1   clipr_0.8.0       htmltools_0.5.7  
[13] ps_1.7.5          fansi_1.0.6       rmarkdown_2.25    R.cache_0.16.0    evaluate_0.22     tibble_3.2.1     
[19] fastmap_1.1.1     yaml_2.3.7        lifecycle_1.0.4   compiler_4.3.2    fs_1.6.3          pkgconfig_2.0.3  
[25] rstudioapi_0.15.0 R.oo_1.25.0       R.utils_2.12.3    digest_0.6.33     R6_2.5.1          utf8_1.2.4       
[31] reprex_2.0.2      pillar_1.9.0      callr_3.7.3       magrittr_2.0.3    checkmate_2.3.1   R.methodsS3_1.8.2
[37] tools_4.3.2       withr_2.5.2  
```

</details>

**Comment by gogonzo** [comment] 2024-01-19 20:11
@donyunardi we have a bug here, `foo()` only is not enough as definition of the `foo` should be also returned. We are going to work on this on Monday.

**Comment by m7pr** [comment] 2024-01-22 09:01
Fixed in https://github.com/insightsengineering/teal.data/pull/263

**Closed** 2024-01-24 15:03 UTC
Labels: bug, core
